metrics_per_position = {
    "Full Back": [
        "Dribbles Stopped %",
        "Carries",
        "OP XG ASSISTED",
        "Successful Dribbles",
        "Successful Crosses",
        "Ball Recoveries",
        "OP Passes Into Box",
        "PR. Pass %",
        "PADJ Interceptions",
        "Aerial Win %"
    ],
    "Centre Back": [
        "Aerial Win %",
        "Dribbles Stopped %",
        "PADJ Tackles",
        "PADJ Interceptions",
        "PADJ Clearances",
        "Defensive Regains",
        "DA OBV",
        "Ball Recoveries",
        "Pass Forward %",
        "PR. Pass %"
    ],
    "Outside Centre Back": [
        "Aerial Win %",
        "Dribbles Stopped %",
        "PADJ Tackles",
        "PADJ Interceptions",
        "PR. Pass %",
        "Carries",
        "Successful Crosses",
        "Dribbles",
        "OP Passes Into Box",
        "OP F3 Passes"
    ],
    "Number 6": [
        "PADJ Tackles",
        "PADJ Interceptions",
        "Pass Forward %",
        "Ball Recoveries",
        "Aerial Win %",
        "Dribbles Stopped %",
        "DA OBV",
        "Deep Progressions",
        "PR. Pass %",
        "Pass OBV",
    ],
    "Number 8": [
        "PINTIN",
        "Shots",
        "Aerial Win %",
        "xG Assisted",
        "OP Key Passes",
        "Dribbles",
        "Carries",
        "OP Passes Into Box",
        "OBV D&C",
        "PR. Pass %"
    ],
    "Number 10": [
        "Shots",
        "xG",
        "Scoring Contribution",
        "OP Key Passes",
        "Successful Dribbles",
        "PINTIN",
        "xG Assisted",
        "Carries",
        "Shooting %",
        "PR. Pass %",
    ],
    "Winger": [
        "xG",
        "Shots",
        "OP Key Passes",
        "Dribbles",
        "Successful Dribbles",
        "OBV",
        "PINTIN",
        "Successful Crosses",
        "xG Assisted",
        "OBV D&C",
    ],
    "Centre Forward A": [
        "NP Goals",
        "Shots",
        "Shooting %",
        "xG",
        "xG/Shot",
        "Shot Touch %",
        "Touches in Box",
        "Carries",
        "Shot OBV",
        "Fouls Won",
    ],
    "Centre Forward B": [
        "NP Goals",
        "Shots",
        "Shooting %",
        "xG",
        "xG/Shot",
        "Shot Touch %",
        "Fouls Won",
        "Pressures",
        "Counterpressures",
        "Aggressive Actions",
    ],
    "Goal Keeper": [
        "GK AGGRESSIVE DIST",
        "CLAIMS %",
        "PR. Pass %",
        "SHOT STOPPING %",
        "OP F3 Passes",
        "GSAA",
        "SAVE %",
        "XSV %",
        "POSITIVE OUTCOME",
        "GOALKEEPER OBV"
    ]
profiles_zcore = {
    key: value for key, value in metrics_per_position.items()
}

